# stats.ps1 — File and line counts per Deckle module
#
# Walks every .csproj under <RepoRoot>\src\, then for each module counts
# files (.cs / .xaml / .xaml.cs / .resw) and lines of code. LOC for .cs
# strips blank lines and single-line // comments; LOC for .xaml strips
# blank lines and <!-- ... --> single-line comments. Generated files
# (.g.cs, .g.i.cs, AssemblyInfo*.cs, GlobalUsings.g.cs) and bin/obj/.vs
# subtrees are excluded.
#
# Use -Detailed to add a per-sub-namespace breakdown inside each module
# (useful for the larger modules — Llm, Whisp, Settings, Playground,
# Deckle host — that organise code in nested folders).
#
# Use -Json <path> to dump the raw counts to a JSON file in addition to
# the console table.

[CmdletBinding()]
param(
    # Override the target worktree. Defaults to the repo containing
    # this script (two levels up: scripts/lib → scripts → repo root).
    [string]$Target,

    # Interactive worktree picker via scripts/lib/_menu.psm1. Overrides
    # -Target. Useful when several worktrees are checked out.
    [switch]$Pick,

    # Print a per-sub-namespace breakdown under each module that has
    # sub-folders. Off by default to keep the main table scannable.
    [switch]$Detailed,

    # Write the raw counts (one entry per module) to this JSON path in
    # addition to the console output.
    [string]$Json
)

$ErrorActionPreference = 'Stop'
$ScriptDir = $PSScriptRoot

if ($Pick) {
    Import-Module (Join-Path $ScriptDir '_menu.psm1') -Force
    $RepoRoot = Select-Worktree -ContextDir $ScriptDir
} elseif ($Target) {
    if (-not (Test-Path $Target)) { throw "Target not found: $Target" }
    $RepoRoot = (Get-Item $Target).FullName
} else {
    $RepoRoot = Split-Path -Parent (Split-Path $ScriptDir)
}

Write-Host "Repo: $RepoRoot" -ForegroundColor DarkGray

$SrcDir = Join-Path $RepoRoot 'src'
if (-not (Test-Path $SrcDir)) { throw "src/ not found under $RepoRoot" }

# Patterns to skip when enumerating source files. Bin/obj/.vs are
# build/IDE state; .g.cs and friends are generated by the XAML/SourceGen
# pipeline, they bloat the count without representing human-authored code.
$skipDirs       = @('bin', 'obj', '.vs', 'Generated Files', 'Properties')
$generatedRegex = '(\.g\.cs|\.g\.i\.cs|\.xaml\.g\.cs|GlobalUsings\.g\.cs|AssemblyInfo\.cs)$'

function Test-SkippedPath {
    param([string]$Path, [string]$RootForRelative)
    # Reject if any path segment between $RootForRelative and the file
    # matches a skipDirs entry, or if the filename matches generatedRegex.
    $rel = $Path.Substring($RootForRelative.Length).TrimStart('\','/')
    # -split with a regex char class — String.Split(char,char) overloads
    # collide here (the second char is interpreted as a count int).
    foreach ($part in ($rel -split '[\\/]')) {
        if ($skipDirs -contains $part) { return $true }
    }
    if ($Path -match $generatedRegex) { return $true }
    return $false
}

function Get-LinesOfCode {
    param([string]$Path, [ValidateSet('cs','xaml')] [string]$Kind)
    # Quick file read — UTF-8 default. Returns count of lines that are
    # not blank and not pure comments.
    $lines = Get-Content -LiteralPath $Path -Encoding UTF8 -ErrorAction SilentlyContinue
    if (-not $lines) { return 0 }
    if ($Kind -eq 'cs') {
        return ($lines | Where-Object {
            $t = $_.Trim()
            ($t -ne '') -and -not $t.StartsWith('//') -and -not $t.StartsWith('/*') -and -not $t.StartsWith('*') -and -not $t.StartsWith('*/')
        }).Count
    } else {
        return ($lines | Where-Object {
            $t = $_.Trim()
            ($t -ne '') -and -not $t.StartsWith('<!--')
        }).Count
    }
}

function Measure-Module {
    param([string]$ModuleRoot)
    $files = Get-ChildItem -LiteralPath $ModuleRoot -Recurse -File -ErrorAction SilentlyContinue |
             Where-Object { -not (Test-SkippedPath -Path $_.FullName -RootForRelative $ModuleRoot) }

    $cs       = $files | Where-Object { $_.Extension -eq '.cs' }
    $xaml     = $files | Where-Object { $_.Extension -eq '.xaml' }
    $xamlCs   = $cs    | Where-Object { $_.Name -like '*.xaml.cs' }
    $csOnly   = $cs    | Where-Object { $_.Name -notlike '*.xaml.cs' }
    $resw     = $files | Where-Object { $_.Extension -eq '.resw' }

    $locCs   = ($cs   | ForEach-Object { Get-LinesOfCode -Path $_.FullName -Kind cs   } | Measure-Object -Sum).Sum
    $locXaml = ($xaml | ForEach-Object { Get-LinesOfCode -Path $_.FullName -Kind xaml } | Measure-Object -Sum).Sum
    if (-not $locCs)   { $locCs   = 0 }
    if (-not $locXaml) { $locXaml = 0 }

    return [pscustomobject]@{
        CountCs     = $csOnly.Count
        CountXaml   = $xaml.Count
        CountXamlCs = $xamlCs.Count
        CountResw   = $resw.Count
        LocCs       = [int]$locCs
        LocXaml     = [int]$locXaml
        LocTotal    = [int]($locCs + $locXaml)
        AllFiles    = $files     # kept around for the detailed sub-folder breakdown
    }
}

function Measure-SubFolder {
    param([string]$ModuleRoot, [string]$SubFolderName, $AllFiles)
    $subRoot = if ($SubFolderName -eq '(flat)') { $ModuleRoot } else { Join-Path $ModuleRoot $SubFolderName }

    # For (flat), only files directly at the module root. For named
    # subfolders, files anywhere underneath that subfolder.
    $sel = if ($SubFolderName -eq '(flat)') {
        $AllFiles | Where-Object { (Split-Path $_.FullName -Parent) -eq $ModuleRoot }
    } else {
        $AllFiles | Where-Object { $_.FullName.StartsWith("$subRoot\", [StringComparison]::OrdinalIgnoreCase) }
    }

    $cs    = $sel | Where-Object { $_.Extension -eq '.cs'   -and $_.Name -notlike '*.xaml.cs' }
    $loc   = ($cs | ForEach-Object { Get-LinesOfCode -Path $_.FullName -Kind cs } | Measure-Object -Sum).Sum
    if (-not $loc) { $loc = 0 }
    return [pscustomobject]@{
        Folder   = $SubFolderName
        CountCs  = $cs.Count
        LocCs    = [int]$loc
    }
}

# ─── Walk every csproj under src/ ───────────────────────────────────────────
$csprojs = Get-ChildItem -LiteralPath $SrcDir -Recurse -Filter '*.csproj' -ErrorAction SilentlyContinue
if (-not $csprojs) { throw "No .csproj found under $SrcDir" }

$rows = foreach ($csproj in $csprojs) {
    $moduleRoot = $csproj.Directory.FullName
    $moduleName = $csproj.Directory.Name
    $m = Measure-Module -ModuleRoot $moduleRoot
    [pscustomobject]@{
        Module    = $moduleName
        Cs        = $m.CountCs
        Xaml      = $m.CountXaml
        XamlCs    = $m.CountXamlCs
        Resw      = $m.CountResw
        LocCs     = $m.LocCs
        LocXaml   = $m.LocXaml
        LocTotal  = $m.LocTotal
        _root     = $moduleRoot
        _files    = $m.AllFiles
    }
}

# Sort by total LOC desc — biggest modules first; gives a quick "where
# does the code live" read.
$rows = $rows | Sort-Object -Property LocTotal -Descending

# ─── Console table ──────────────────────────────────────────────────────────
Write-Host ""
$rows | Format-Table -AutoSize -Property `
    @{Name='Module';     Expression={$_.Module}},
    @{Name='.cs';        Expression={$_.Cs};       Alignment='Right'},
    @{Name='.xaml';      Expression={$_.Xaml};     Alignment='Right'},
    @{Name='.xaml.cs';   Expression={$_.XamlCs};   Alignment='Right'},
    @{Name='.resw';      Expression={$_.Resw};     Alignment='Right'},
    @{Name='LOC (cs)';   Expression={'{0:N0}' -f $_.LocCs};    Alignment='Right'},
    @{Name='LOC (xaml)'; Expression={'{0:N0}' -f $_.LocXaml};  Alignment='Right'},
    @{Name='LOC total';  Expression={'{0:N0}' -f $_.LocTotal}; Alignment='Right'} |
    Out-Host

# Totals
$tot = [pscustomobject]@{
    Cs       = ($rows | Measure-Object -Property Cs       -Sum).Sum
    Xaml     = ($rows | Measure-Object -Property Xaml     -Sum).Sum
    XamlCs   = ($rows | Measure-Object -Property XamlCs   -Sum).Sum
    Resw     = ($rows | Measure-Object -Property Resw     -Sum).Sum
    LocCs    = ($rows | Measure-Object -Property LocCs    -Sum).Sum
    LocXaml  = ($rows | Measure-Object -Property LocXaml  -Sum).Sum
    LocTotal = ($rows | Measure-Object -Property LocTotal -Sum).Sum
}
Write-Host ("TOTAL  {0} .cs  {1} .xaml  {2} .xaml.cs  {3} .resw  /  LOC: {4:N0} cs + {5:N0} xaml = {6:N0}" -f `
    $tot.Cs, $tot.Xaml, $tot.XamlCs, $tot.Resw, $tot.LocCs, $tot.LocXaml, $tot.LocTotal) -ForegroundColor Cyan
Write-Host ""

# ─── Detailed sub-folder breakdown ─────────────────────────────────────────
if ($Detailed) {
    foreach ($row in $rows) {
        # Discover first-level subfolders inside the module (skipping
        # bin/obj/.vs). Always include a synthetic "(flat)" bucket for
        # the files at the module root.
        $subDirs = Get-ChildItem -LiteralPath $row._root -Directory -ErrorAction SilentlyContinue |
                   Where-Object { $skipDirs -notcontains $_.Name } |
                   Sort-Object Name
        if ($subDirs.Count -eq 0) { continue }   # flat module — nothing to break down

        Write-Host ("─── {0} ─────────────────────────" -f $row.Module) -ForegroundColor DarkCyan
        $buckets = @('(flat)') + ($subDirs | ForEach-Object { $_.Name })
        $subRows = foreach ($b in $buckets) {
            Measure-SubFolder -ModuleRoot $row._root -SubFolderName $b -AllFiles $row._files
        }
        $subRows | Where-Object { $_.CountCs -gt 0 -or $_.Folder -eq '(flat)' } | Format-Table -AutoSize -Property `
            @{Name='Folder';   Expression={$_.Folder}},
            @{Name='.cs';      Expression={$_.CountCs}; Alignment='Right'},
            @{Name='LOC';      Expression={'{0:N0}' -f $_.LocCs}; Alignment='Right'} | Out-Host
        Write-Host ""
    }
}

# ─── Optional JSON dump ─────────────────────────────────────────────────────
if ($Json) {
    $rows | Select-Object Module, Cs, Xaml, XamlCs, Resw, LocCs, LocXaml, LocTotal |
        ConvertTo-Json -Depth 3 |
        Set-Content -LiteralPath $Json -Encoding UTF8
    Write-Host "Wrote $Json" -ForegroundColor DarkGray
}
